# Site settings
title: "Blog - Vyavsaay ERP"
description: "An informative blog for all IT (Information Technology) related queries for your business"
googleplus: "https://plus.google.com/+Vyavsaayindia"
facebook: "https://www.facebook.com/vyavsaayindia/"
twitter: "https://twitter.com/VyavsaayIndia"
linkedin: "https://www.linkedin.com/company/vyavsaay-erp"
disqus: "vyavsaay"
author: "Ashish Goyal"