#!/bin/bash
#
#	/etc/init.d/sms_daemon
#
# Starts the at daemon
#
# chkconfig: 345 95 5
# description: Runs the sms daemon.
# processname: sms_daemon
 
# Source function library.
#. /etc/init.d/functions
 
#startup values
log=/var/log/sms_daemon.log
 
#verify that the executable exists
test -x ./sms_daemon.php || exit 0RETVAL=0
 
#
#	Set prog, proc and bin variables.
#
prog="sms_daemon"
proc=/var/lock/sms_daemon
bin=./sms_daemon.php
 
start() {
	# Check if Daemon is already running
	if [ ! -f $proc ]; then
	    echo -n $"Starting $prog: "
	    $bin --log=$log
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $proc
	    echo
	fi
 
	return $RETVAL
}
 
stop() {
	echo -n $"Stopping $prog: "
	pkill $bin
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $proc
	echo
        return $RETVAL
}
 
restart() {
	stop
	start
}	
 
reload() {
	restart
}	
 
status_at() {
 	status $bin
}
 
case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
condrestart)
        if [ -f $proc ]; then
            restart
        fi
        ;;
status)
	status_at
	;;
*)
 
echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac
 
exit $?
exit $RETVAL